[wallpaper]
3306588730 = "芙宁娜"
3409595232 = "初音未来"
3353913172 = "山田凉"
2992022633 = "测试"

[path]
wallpaper_engine_config = "D:/Application/STEAM/steamapps/common/wallpaper_engine/config.json"

[config]
enable_default_icon_group = true  # 是否启用默认图标组