[package]
name = "set_mouse_registry"
version = "0.1.0"
edition = "2021"

[lib]
name = "set_mouse_registry"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
winreg = "0.55"
winapi = { version = "0.3", features = ["winuser", "minwindef", "ntdef"] }