[mouses]
Arrow = "mouses\\123\\11.ani"
Help = "mouses\\123\\15.ani"
AppStarting = "mouses\\123\\1.ani"
Wait = ""
Crosshair = ""
IBeam = ""
Handwriting = ""
No = ""
SizeNS = ""
SizeWE = ""
SizeNWSE = ""
SizeNESW = ""
SizeAll = ""
Hand = ""
UpArrow = ""
