[mouses]
Arrow = "mouses\\默认\\1.cur"          # 箭头光标
Help = "mouses\\默认\\2.cur"          # 帮助光标
AppStarting = "mouses\\默认\\3.ani"   # 程序启动光标
Wait = "mouses\\默认\\4.ani"               # 等待光标
Crosshair = ""          # 十字线光标
IBeam = ""              # 文本输入光标
Handwriting = "mouses\\默认\\7.cur"        # 手写光标
No = "mouses\\默认\\8.cur"                 # 禁止光标
SizeNS = "mouses\\默认\\9.cur"              # 垂直调整大小光标
SizeWE = "mouses\\默认\\10.cur"              # 水平调整大小光标
SizeNWSE = "mouses\\默认\\11.cur"            # 对角线调整大小光标（左上-右下）
SizeNESW = "mouses\\默认\\12.cur"            # 对角线调整大小光标（右上-左下）
SizeAll = "mouses\\默认\\13.cur"              # 全方向调整大小光标
Hand = "mouses\\默认\\15.cur"                # 链接选择
UpArrow = "mouses\\默认\\0.cur"             # 向上箭头光标
