[mouses]
Arrow = "mouses\\默认\\1.cur"
Help = "mouses\\默认\\1.cur"
AppStarting = "mouses\\默认\\1.cur"
Wait = "mouses\\默认\\1.cur"
Crosshair = "mouses\\默认\\1.cur"
IBeam = "mouses\\默认\\1.cur"
Handwriting = "mouses\\默认\\1.cur"
No = "mouses\\默认\\1.cur"
SizeNS = "mouses\\默认\\1.cur"
SizeWE = "mouses\\默认\\1.cur"
SizeNWSE = "mouses\\默认\\1.cur"
SizeNESW = "mouses\\默认\\1.cur"
SizeAll = "mouses\\默认\\1.cur"
PersonSelect = "mouses\\默认\\1.cur"
Hand = "mouses\\默认\\1.cur"
UpArrow = "mouses\\默认\\1.cur"
