[mouses]
Arrow = "mouses\\miku\\Normal Select.ani"
Help = "mouses\\miku\\Help Select.ani"
AppStarting = "mouses\\miku\\Work.ani"
Wait = "mouses\\miku\\Busy.ani"
Crosshair = ""
IBeam = "mouses\\miku\\Text Select.ani"
Handwriting = "mouses\\miku\\handwriting.ani"
No = "mouses\\miku\\Unavailable.ani"
SizeNS = "mouses\\miku\\Vertical Resize.ani"
SizeWE = "mouses\\miku\\Horizontal Resize.ani"
SizeNWSE = "mouses\\miku\\Diagonal Resize 1.ani"
SizeNESW = "mouses\\miku\\Diagonal Resize 2.ani"
SizeAll = "mouses\\miku\\Move.ani"
PersonSelect = ""
Hand = "mouses\\miku\\Link.ani"
UpArrow = ""
