[mouses]
Arrow = ""
Help = ""
AppStarting = ""
Wait = ""
Crosshair = ""
IBeam = ""
Handwriting = ""
No = ""
SizeNS = ""
SizeWE = ""
SizeNWSE = ""
SizeNESW = ""
SizeAll = ""
PersonSelect = ""
Hand = ""
UpArrow = ""
