[mouses]
Arrow = "mouses\\芙宁娜\\1.ani"
Help = "mouses\\芙宁娜\\2.ani"
AppStarting = "mouses\\芙宁娜\\3.ani"
Wait = "mouses\\芙宁娜\\4.ani"
Crosshair = "mouses\\芙宁娜\\5.ani"
IBeam = "mouses\\芙宁娜\\6.ani"
Handwriting = "mouses\\芙宁娜\\7.ani"
No = "mouses\\芙宁娜\\8.ani"
SizeNS = "mouses\\芙宁娜\\9.ani"
SizeWE = "mouses\\芙宁娜\\10.ani"
SizeNWSE = "mouses\\芙宁娜\\11.ani"
SizeNESW = "mouses\\芙宁娜\\12.ani"
SizeAll = "mouses\\芙宁娜\\13.ani"
PersonSelect = "mouses\\芙宁娜\\14.ani"
Hand = "mouses\\芙宁娜\\15.ani"
UpArrow = "mouses\\芙宁娜\\16.ani"
