[mouses]
Arrow = "mouses\\芙宁娜\\1.ani"
Help = ""
AppStarting = "mouses\\芙宁娜\\1.ani"
Wait = ""
Crosshair = ""
IBeam = "mouses\\芙宁娜\\1.ani"
Handwriting = ""
No = "mouses\\芙宁娜\\1.ani"
SizeNS = ""
SizeWE = ""
SizeNWSE = ""
SizeNESW = ""
SizeAll = ""
PersonSelect = ""
Hand = ""
UpArrow = ""
