[mouses]
Arrow = "mouses\\初音未来\\Normal Select.ani"
Help = "mouses\\初音未来\\Help Select.ani"
AppStarting = "mouses\\初音未来\\Work.ani"
Wait = "mouses\\初音未来\\Busy.ani"
Crosshair = "mouses\\初音未来\\Precision Select.ani"
IBeam = "mouses\\初音未来\\Text Select.ani"
Handwriting = "mouses\\初音未来\\handwriting.ani"
No = "mouses\\初音未来\\Unavailable.ani"
SizeNS = "mouses\\初音未来\\Vertical Resize.ani"
SizeWE = "mouses\\初音未来\\Horizontal Resize.ani"
SizeNWSE = "mouses\\初音未来\\Diagonal Resize 1.ani"
SizeNESW = "mouses\\初音未来\\Diagonal Resize 2.ani"
SizeAll = "mouses\\初音未来\\Move.ani"
Hand = "mouses\\初音未来\\Link.ani"
UpArrow = ""
